language: python


env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.8
        - SETUP_CMD='test'
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib scipy'
        - SETUP_XVFB=True
        - ON_TRAVIS=True
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''

matrix:
    include:

        - python: 3.7
          env: TOXENV='py37-test'
          name: "Python 3.7 with minimal dependencies"

        - python: 3.7
          env: TOXENV='py37-test-all'
          name: "Python 3.7 with all dependencies"

        # Do a coverage test in Python 3.
        # make sure *everything* is run for coverage tests
        - env: SETUP_CMD='test --coverage'
          name: coverage

        - python: 3.8
          env: TOXENV='py38-test-all-dev'
          name: "Python 3.8, all dependencies, and dev versions of key dependencies"

        - language: c
          os: osx
          env: PYTHON_VERSION=3.7 TOXENV='py37-test-all'
          name: "Python 3.7 with all dependencies on MacOS X"

        - language: c
          os: windows
          env: PYTHON_VERSION=3.7 TOXENV='py37-test-all-dev'
          name: "Python 3.7, all dependencies, and dev versions of key dependencies on Windows"

        - python: 3.8
          env: TOXENV='build_docs'
          name: "Documentation"

before_install:
    # We need a full clone to make sure setuptools_scm
    # works properly
    - git fetch --unshallow .
    - git fetch --depth=1000000

    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        export DISPLAY=:99.0;
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset;
      fi

install:
    # language: python is only available for Linux, so for other platforms
    # we need to use ci-helpers to set up Python.
    - if [[ $TRAVIS_OS_NAME == osx || $TRAVIS_OS_NAME == windows ]]; then
        git clone git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi


script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS

after_success:
    - pip install coveralls coverage
    - coverage combine .tmp/*/.coverage
    - coverage report
    - coveralls
